/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Backpack.glb -T 
Files: Backpack.glb [54.28KB] > F:\My Documents\Sites games\school-run\public\models\Backpack-transformed.glb [6.54KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelBackpack(props) {
  const { nodes, materials } = useGLTF('models/Backpack-transformed.glb')
  return (
    <group {...props} dispose={null} position={[0, -2, 0]}>
      <mesh geometry={nodes['Backpack_Cube006-Mesh'].geometry} material={materials.Backpack} />
      <mesh geometry={nodes['Backpack_Cube006-Mesh_1'].geometry} material={materials.Silver} />
      <mesh geometry={nodes['Backpack_Cube006-Mesh_2'].geometry} material={materials.Brown2} />
    </group>
  )
}

useGLTF.preload('models/Backpack-transformed.glb')
