/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const link = `${process.env.NEXT_PUBLIC_CDN}games/School+Run/Blood+Splat.glb`

export function BloodSplatModel(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Blood_2.geometry}
        material={materials['Atlas.039']}
        scale={100}
      />
    </group>
  )
}

useGLTF.preload(link)
