/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'
// import getModelSource from '@/util/getModelSource';

// const link = getModelSource(
//   `games/Assets/kenney_furniture-kit/Models/GLTF format/bookcaseClosedDoors.glb`,
//   `games/Assets/kenney_furniture-kit/Models/GLTF format/bookcaseClosedDoors.glb`
// );

// export function BookcaseClosedDoorsModel(props) {
//   const { nodes, materials } = useGLTF(link)
//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes['bookcaseClosedDoors(Clone)'].geometry}
//         material={materials.wood}>
//         <group position={[0.04, 0.115, -0.02]}>
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Mesh_doorLeft.geometry}
//             material={materials.wood}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Mesh_doorLeft_1.geometry}
//             material={materials.metal}
//           />
//         </group>
//         <group position={[0.36, 0.115, -0.02]}>
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Mesh_doorRight.geometry}
//             material={materials.metal}
//           />
//           <mesh
//             castShadow
//             receiveShadow
//             geometry={nodes.Mesh_doorRight_1.geometry}
//             material={materials.wood}
//           />
//         </group>
//       </mesh>
//     </group>
//   )
// }

// useGLTF.preload(link)