/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 BrokenWindow.glb -T 
Files: BrokenWindow.glb [20.47KB] > F:\My Documents\Sites games\school-run\public\models\BrokenWindow-transformed.glb [3.67KB] (82%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelBrokenWindow(props) {
  const { nodes, materials } = useGLTF('models/BrokenWindow-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat24} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat20} />
    </group>
  )
}

useGLTF.preload('models/BrokenWindow-transformed.glb')
