/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/kenney_furniture-kit/Models/GLTF format/chair.glb`

export function ChairModel(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['chair(Clone)'].geometry}
        material={materials.wood}
      />
    </group>
  )
}

useGLTF.preload(link)
