/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\computerScreen.glb -T 
Files: .\computerScreen.glb [6.4KB] > F:\My Documents\Sites games\school-run\public\models\computerScreen-transformed.glb [2.22KB] (65%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

// import getAssetSource from "@/util/getAssetSource";
import getAssetSource from "@articles-media/articles-dev-box/getAssetSource";

const link = getAssetSource(`models/computerScreen-transformed.glb`);

export function ModelComputerScreen(props) {
    const { nodes, materials } = useGLTF(link);
    return (
        <group
            {...props}
            dispose={null}
        >
            <mesh
                geometry={nodes.Mesh_computerScreen.geometry}
                material={materials.metalDark}
            />
            <mesh
                geometry={nodes.Mesh_computerScreen_1.geometry}
                material={materials.metal}
            />
        </group>
    );
}

useGLTF.preload(link);
