/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\computerKeyboard.glb -T 
Files: .\computerKeyboard.glb [3.48KB] > F:\My Documents\Sites games\school-run\public\models\computerKeyboard-transformed.glb [2.08KB] (40%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

// import getAssetSource from "@/util/getAssetSource";
import getAssetSource from '@articles-media/articles-dev-box/getAssetSource';

const link = getAssetSource(
  `models/computerKeyboard-transformed.glb`
);

export function ModelComputerKeyboard(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_computerKeyboard.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.Mesh_computerKeyboard_1.geometry} material={materials.metalMedium} />
    </group>
  )
}

useGLTF.preload(link)
