/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/kenney_furniture-kit/Models/GLTF format/computerScreen.glb`

export function ComputerScreenModel(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_computerScreen.geometry}
        material={materials.metalDark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_computerScreen_1.geometry}
        material={materials.metal}
      />
    </group>
  )
}

useGLTF.preload(link)
