/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/kenney_furniture-kit/Models/GLTF format/desk.glb`

export function DeskModel(props) {
    const { nodes, materials } = useGLTF(link)
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['desk(Clone)'].geometry}
                material={materials.wood}>
                <group position={[0.04, 0.274, -0.164]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh_drawer.geometry}
                        material={materials.wood}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Mesh_drawer_1.geometry}
                        material={materials.metal}
                    />
                </group>
            </mesh>
        </group>
    )
}

useGLTF.preload(link)
