/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 models\doorway.glb --output output\DOorway.js 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelDoorway(props) {
  const { nodes, materials } = useGLTF('https://cdn.articles.media/games/Assets/kenney_furniture-kit/Models/GLTF format/doorway.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['doorway(Clone)'].geometry} material={materials.wood}>
        <group position={[0.028, 0, -0.045]}>
          <mesh geometry={nodes.Mesh_door.geometry} material={materials.wood} />
          <mesh geometry={nodes.Mesh_door_1.geometry} material={materials.metal} />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('https://cdn.articles.media/games/Assets/kenney_furniture-kit/Models/GLTF format/doorway.glb')
