/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const link = `${process.env.NEXT_PUBLIC_CDN}games/School+Run/Fps+Rig+AKM.glb`

export function FpsRigAkmModel(props) {

    const group = useRef()
    const { nodes, materials, animations } = useGLTF(link)
    const { actions } = useAnimations(animations, group)

    useEffect(() => {

        // console.log("Actions", actions)

        // actions[`Armature|Reload`].play();

    }, [actions]);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Root_Scene">
                <group name="RootNode">
                    <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={336.502}>
                        <primitive object={nodes.UpperArmL} />
                        <primitive object={nodes.UpperArmR001} />
                        <primitive object={nodes.Root} />
                    </group>
                    <group name="ArmModel" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <skinnedMesh
                            name="ArmModel_1"
                            geometry={nodes.ArmModel_1.geometry}
                            material={materials.Shirt}
                            skeleton={nodes.ArmModel_1.skeleton}
                        />
                        <skinnedMesh
                            name="ArmModel_2"
                            geometry={nodes.ArmModel_2.geometry}
                            material={materials.Skin}
                            skeleton={nodes.ArmModel_2.skeleton}
                        />
                        <skinnedMesh
                            name="ArmModel_3"
                            geometry={nodes.ArmModel_3.geometry}
                            material={materials.Glove}
                            skeleton={nodes.ArmModel_3.skeleton}
                        />
                    </group>
                    <group
                        name="AKM_model"
                        position={[-1.817, 1.512, 1.724]}
                        rotation={[-Math.PI / 2, 0, Math.PI]}
                        scale={[53.699, 37.608, 62.9]}>
                        <skinnedMesh
                            name="AKM_model_1"
                            geometry={nodes.AKM_model_1.geometry}
                            material={materials.Metal1}
                            skeleton={nodes.AKM_model_1.skeleton}
                        />
                        <skinnedMesh
                            name="AKM_model_2"
                            geometry={nodes.AKM_model_2.geometry}
                            material={materials.Metal2}
                            skeleton={nodes.AKM_model_2.skeleton}
                        />
                        <skinnedMesh
                            name="AKM_model_3"
                            geometry={nodes.AKM_model_3.geometry}
                            material={materials['Black.002']}
                            skeleton={nodes.AKM_model_3.skeleton}
                        />
                        <skinnedMesh
                            name="AKM_model_4"
                            geometry={nodes.AKM_model_4.geometry}
                            material={materials.DarkPlastic}
                            skeleton={nodes.AKM_model_4.skeleton}
                        />
                        <skinnedMesh
                            name="AKM_model_5"
                            geometry={nodes.AKM_model_5.geometry}
                            material={materials.Wood}
                            skeleton={nodes.AKM_model_5.skeleton}
                        />
                        <skinnedMesh
                            name="AKM_model_6"
                            geometry={nodes.AKM_model_6.geometry}
                            material={materials.BakeliteMag}
                            skeleton={nodes.AKM_model_6.skeleton}
                        />
                        <skinnedMesh
                            name="AKM_model_7"
                            geometry={nodes.AKM_model_7.geometry}
                            material={materials.Metal3}
                            skeleton={nodes.AKM_model_7.skeleton}
                        />
                        <skinnedMesh
                            name="AKM_model_8"
                            geometry={nodes.AKM_model_8.geometry}
                            material={materials.Bullet1}
                            skeleton={nodes.AKM_model_8.skeleton}
                        />
                        <skinnedMesh
                            name="AKM_model_9"
                            geometry={nodes.AKM_model_9.geometry}
                            material={materials.Bullet2}
                            skeleton={nodes.AKM_model_9.skeleton}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload(link)
