/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\FpsRigAkm.glb -T 
Files: .\FpsRigAkm.glb [870.4KB] > F:\My Documents\Sites games\school-run\public\models\FpsRigAkm-transformed.glb [75.12KB] (91%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import getAssetSource from "@/util/getAssetSource";

const link = getAssetSource(
  `models/FpsRigAkm-transformed.glb`
);

export function ModelFpsRigAkm(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF(link)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={336.502}>
          <primitive object={nodes.UpperArmL} />
          <primitive object={nodes.UpperArmR001} />
          <primitive object={nodes.Root} />
        </group>
        <group name="ArmModel" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <skinnedMesh name="ArmModel_1" geometry={nodes.ArmModel_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.ArmModel_1.skeleton} />
          <skinnedMesh name="ArmModel_2" geometry={nodes.ArmModel_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.ArmModel_2.skeleton} />
          <skinnedMesh name="ArmModel_3" geometry={nodes.ArmModel_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.ArmModel_3.skeleton} />
        </group>
        <group name="AKM_model" position={[-1.817, 1.512, 1.724]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[53.699, 37.608, 62.9]}>
          <skinnedMesh name="AKM_model_1" geometry={nodes.AKM_model_1.geometry} material={materials.PaletteMaterial001} skeleton={nodes.AKM_model_1.skeleton} />
          <skinnedMesh name="AKM_model_2" geometry={nodes.AKM_model_2.geometry} material={materials.PaletteMaterial001} skeleton={nodes.AKM_model_2.skeleton} />
          <skinnedMesh name="AKM_model_3" geometry={nodes.AKM_model_3.geometry} material={materials.PaletteMaterial001} skeleton={nodes.AKM_model_3.skeleton} />
          <skinnedMesh name="AKM_model_4" geometry={nodes.AKM_model_4.geometry} material={materials.PaletteMaterial001} skeleton={nodes.AKM_model_4.skeleton} />
          <skinnedMesh name="AKM_model_5" geometry={nodes.AKM_model_5.geometry} material={materials.PaletteMaterial001} skeleton={nodes.AKM_model_5.skeleton} />
          <skinnedMesh name="AKM_model_6" geometry={nodes.AKM_model_6.geometry} material={materials.PaletteMaterial001} skeleton={nodes.AKM_model_6.skeleton} />
          <skinnedMesh name="AKM_model_7" geometry={nodes.AKM_model_7.geometry} material={materials.PaletteMaterial001} skeleton={nodes.AKM_model_7.skeleton} />
          <skinnedMesh name="AKM_model_8" geometry={nodes.AKM_model_8.geometry} material={materials.PaletteMaterial001} skeleton={nodes.AKM_model_8.skeleton} />
          <skinnedMesh name="AKM_model_9" geometry={nodes.AKM_model_9.geometry} material={materials.PaletteMaterial001} skeleton={nodes.AKM_model_9.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(link)
