/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Human hand.glb -T 
Files: Human hand.glb [29.98KB] > F:\My Documents\Sites games\school-run\public\models\Human hand-transformed.glb [4.74KB] (84%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelHand(props) {
  const { nodes, materials } = useGLTF('models/Human hand-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pasted__Arm_pasted__Body_LowRes_group.geometry} material={materials.lambert2SG} />
    </group>
  )
}

useGLTF.preload('models/Human hand-transformed.glb')
