/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/Pear.glb`

export function PearModel(props) {

    const { nodes, materials } = useGLTF(link)

    return (
        <group {...props} dispose={null}>
            <mesh castShadow receiveShadow geometry={nodes.pear_1.geometry} material={materials.green} />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.pear_1_1.geometry}
                material={materials.brown}
            />
        </group>
    )
}

useGLTF.preload(link)
