/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\televisionVintage.glb -T 
Files: .\televisionVintage.glb [19.39KB] > F:\My Documents\Sites games\school-run\public\models\televisionVintage-transformed.glb [4.69KB] (76%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import getAssetSource from "@/util/getAssetSource";

const link = getAssetSource(
  `models/televisionVintage-transformed.glb`
);

export function ModelTelevisionVintage(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_televisionVintage.geometry} material={materials.metal} />
      <mesh geometry={nodes.Mesh_televisionVintage_1.geometry} material={materials.wood} />
      <mesh geometry={nodes.Mesh_televisionVintage_2.geometry} material={materials.metalMedium} />
      <mesh geometry={nodes.Mesh_televisionVintage_3.geometry} material={materials.metalDark} />
    </group>
  )
}

useGLTF.preload(link)
