/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/kenney_furniture-kit/Models/GLTF format/televisionVintage.glb`

export function TelevisionVintageModel(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_televisionVintage.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_televisionVintage_1.geometry}
        material={materials.wood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_televisionVintage_2.geometry}
        material={materials.metalMedium}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_televisionVintage_3.geometry}
        material={materials.metalDark}
      />
    </group>
  )
}

useGLTF.preload(link)
