/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 UnbrokenWindow.glb -T 
Files: UnbrokenWindow.glb [8.9KB] > F:\My Documents\Sites games\school-run\public\models\UnbrokenWindow-transformed.glb [2.44KB] (73%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelUnbrokenWindow(props) {
  const { nodes, materials } = useGLTF('models/UnbrokenWindow-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat24} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat20} />
    </group>
  )
}

useGLTF.preload('models/UnbrokenWindow-transformed.glb')
