/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\WetFloorSign.glb -T 
Files: .\WetFloorSign.glb [1.74MB] > F:\My Documents\Sites games\school-run\public\models\WetFloorSign-transformed.glb [165.54KB] (90%)
Author: louis-muir (https://sketchfab.com/louir-muir)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wet-floor-sign-d340f904c4684645a4e5282b5fbe963b
Title: Wet Floor Sign
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import getAssetSource from "@/util/getAssetSource";

const link = getAssetSource(
  `models/WetFloorSign-transformed.glb`
);

export function ModelWetFloorSign(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wet_floor_sign_lambert1_0.geometry}
        material={materials.lambert1}
        position={[0, 0, 0]}
        scale={0.015}
      />
    </group>
  )
}

useGLTF.preload(link)
