/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: louis-muir (https://sketchfab.com/louir-muir)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wet-floor-sign-d340f904c4684645a4e5282b5fbe963b
Title: Wet Floor Sign
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function WetFloorSign(props) {
  const { nodes, materials } = useGLTF('models/wet_floor_sign.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wet_floor_sign_lambert1_0.geometry}
        material={materials.lambert1}
        position={[0, 0, 0]}
        scale={0.015}
      />
    </group>
  )
}

useGLTF.preload('models/wet_floor_sign.glb')
