/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\witch.gltf -T 
Files: .\witch.gltf [212.04KB] > F:\My Documents\Sites games\school-run\public\models\witch-transformed.glb [19.53KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import getAssetSource from '@/util/getAssetSource';

const link = getAssetSource(
  `models/witch-transformed.glb`,
);

export function ModelWitch(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube020.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Cube020_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh geometry={nodes.character_witchHead.geometry} material={materials.PaletteMaterial003} position={[0, 0.704, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(link)
