/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const link = `${process.env.NEXT_PUBLIC_CDN}games/Race Game/bear.gltf`

export default function Bear(props) {

    const { color } = props;

    const { nodes, materials } = useGLTF(link);

    const originalMaterial = materials["BrownDark.036"];
    const newMaterial = originalMaterial.clone();

    // TODO - Check if valid hex then set color?

    if (color) {
        newMaterial.color.set(color);
    }

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.character_bear.geometry}
                material={newMaterial}
                rotation={[Math.PI / 2, 0, 0]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.character_bearArmLeft.geometry}
                    material={newMaterial}
                    position={[0.204, 0, -0.634]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.character_bearArmRight.geometry}
                    material={newMaterial}
                    position={[-0.204, 0, -0.634]}
                />
                <group position={[0, 0, -0.704]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube1337.geometry}
                        material={materials["Black.025"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube1337_1.geometry}
                        material={newMaterial}
                    />
                </group>
            </mesh>
        </group>
    );
}

useGLTF.preload(link);