/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const link = `${process.env.NEXT_PUBLIC_CDN}games/School+Run/SuitWoman.glb`

export function SuitWomanModel(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF(link)
    const { actions } = useAnimations(animations, group)

    useEffect(() => {

        console.log("Actions", actions)

        actions["CharacterArmature|Death"].play();

        // return

        // actions["CharacterArmature|Death"].paused = true;
        // actions["CharacterArmature|Death"].time = 10;

        let action = actions["CharacterArmature|Death"]

        action.paused = true; // Pause the animation
        action.time = action.getClip().duration; // Set time to the last frame
        // action.update(0); // Update the animation to the last frame

        return () => {

        };

    }, [actions]);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Root_Scene">
                <group name="RootNode">
                    <group name="CharacterArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <primitive object={nodes.Root} />
                    </group>
                    <group name="Suit_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <skinnedMesh
                            name="Suit_Body_1"
                            geometry={nodes.Suit_Body_1.geometry}
                            material={materials.Black}
                            skeleton={nodes.Suit_Body_1.skeleton}
                        />
                        <skinnedMesh
                            name="Suit_Body_2"
                            geometry={nodes.Suit_Body_2.geometry}
                            material={materials.White}
                            skeleton={nodes.Suit_Body_2.skeleton}
                        />
                        <skinnedMesh
                            name="Suit_Body_3"
                            geometry={nodes.Suit_Body_3.geometry}
                            material={materials.Skin}
                            skeleton={nodes.Suit_Body_3.skeleton}
                        />
                    </group>
                    <group name="Suit_Feet" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <skinnedMesh
                            name="Suit_Feet_1"
                            geometry={nodes.Suit_Feet_1.geometry}
                            material={materials.Black}
                            skeleton={nodes.Suit_Feet_1.skeleton}
                        />
                        <skinnedMesh
                            name="Suit_Feet_2"
                            geometry={nodes.Suit_Feet_2.geometry}
                            material={materials.Skin}
                            skeleton={nodes.Suit_Feet_2.skeleton}
                        />
                    </group>
                    <group name="Suit_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                        <skinnedMesh
                            name="Suit_Head_1"
                            geometry={nodes.Suit_Head_1.geometry}
                            material={materials.Skin}
                            skeleton={nodes.Suit_Head_1.skeleton}
                        />
                        <skinnedMesh
                            name="Suit_Head_2"
                            geometry={nodes.Suit_Head_2.geometry}
                            material={materials.Hair_Blond}
                            skeleton={nodes.Suit_Head_2.skeleton}
                        />
                        <skinnedMesh
                            name="Suit_Head_3"
                            geometry={nodes.Suit_Head_3.geometry}
                            material={materials.Hair_Brown}
                            skeleton={nodes.Suit_Head_3.skeleton}
                        />
                        <skinnedMesh
                            name="Suit_Head_4"
                            geometry={nodes.Suit_Head_4.geometry}
                            material={materials.Brown}
                            skeleton={nodes.Suit_Head_4.skeleton}
                        />
                    </group>
                    <skinnedMesh
                        name="Suit_Legs"
                        geometry={nodes.Suit_Legs.geometry}
                        material={materials.Black}
                        skeleton={nodes.Suit_Legs.skeleton}
                        rotation={[-Math.PI / 2, 0, 0]}
                        scale={100}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload(link)
