/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const link = `${process.env.NEXT_PUBLIC_CDN}games/Race Game/witch.gltf`

export default function Witch(props) {

    const { color } = props;

    // try {
    //     const { nodes, materials } = useGLTF(link);
    // } catch {
    //     console.log("Failed fetch")
    // }

    const { nodes, materials } = useGLTF(link);

    const originalMaterial = materials["Purple.008"];
    const newMaterial = originalMaterial.clone();

    // TODO - Check if valid hex then set color?

    if (color) {
        newMaterial.color.set(color);
    }

    return (
        <group {...props} dispose={null}>
            <group rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube020.geometry}
                    material={newMaterial}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube020_1.geometry}
                    material={materials["Black.019"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube020_2.geometry}
                    material={materials["Yellow.010"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube020_3.geometry}
                    material={materials["GreenLight.003"]}
                />
                <group position={[0.204, 0, -0.634]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube018.geometry}
                        material={materials["GreenLight.003"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube018_1.geometry}
                        material={newMaterial}
                    />
                </group>
                <group position={[-0.204, 0, -0.634]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube019.geometry}
                        material={newMaterial}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube019_1.geometry}
                        material={materials["GreenLight.003"]}
                    />
                </group>
                <group position={[0, 0, -0.704]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube017.geometry}
                        material={materials["Black.019"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube017_1.geometry}
                        material={materials["GreenLight.003"]}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube017_2.geometry}
                        material={materials["Green.003"]}
                    />
                    <group position={[0, -0.071, -0.768]} rotation={[-0.264, 0, 0]}>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube016.geometry}
                            material={newMaterial}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube016_1.geometry}
                            material={materials["Black.019"]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cube016_2.geometry}
                            material={materials["Yellow.010"]}
                        />
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload(link);